### ISSUE TITLE
Support Content-Type filtering

### ISSUE THREAD

**Issue by dausruddin** [caddyserver/replace-response#11]
Hi. By default, this module make replacement in every single file. I am not sure how far true is that statement, but at least in my case it made replacement in html, css, and js.

Example:
```
:8081 {
    tls internal

    reverse_proxy https://caddyserver.com {
        header_up Host {upstream_hostport}
        header_up X-Forwarded-Host {host}
        header_up -Accept-Encoding

    }

    replace re "(?i)caddy" "C4DDY"

}
```

Not only in the webpage, but it made replacement in `http://localhost:8081/resources/js/common.js` as well.

My request is, let us define the type of file we want to make replacement in.
I am not sure how it affect performance and resources, but this option will be a great one to have.

Thank you!

**Comment by mholt** [comment]
That's because without a [request matcher](https://caddyserver.com/docs/caddyfile/matchers), the replace middleware will be invoked for all requests. Like with other Caddy directives, simply use a request matcher to only filter requests you want to do replacements on.

**Comment by dausruddin** [comment]
Let say I have

- a rule for index
- a rule for index and js
- a rule for index, js, and css
- a rule for css and js

This would leave me with 4 `reverse_proxy` directive at least I guess? 

Also a question. For multiple path, I need to use named matcher?

**Comment by dausruddin** [comment]
Honestly I am so clueless. How do I get content-type?
This is my try without success. 

```
:8081 {
    tls internal

    @html {
        expression {http.reverse_proxy.header.Content-Type}.contains("html")
    }
    reverse_proxy @html https://caddyserver.com {
        header_up Host {upstream_hostport}
        header_up X-Forwarded-Host {host}
        header_up -Accept-Encoding

    }

    replace re "(?i)a" "A"
}
```

Even if this is working, how do I `replace` specific to @html? Let say I got them working and have 3 named parameters @html, @js, and @css, with individual `reverse_proxy`. How do I make specific replace rules for each of them? Do i need to use [handle_response](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#handle_response) ?

**Comment by mholt** [comment]
Request matchers match on properties of the request, not the response. So you simply select the _requests_ that you will want to filter the response bodies on.

**Comment by dausruddin** [comment]
So use extension, something like `reverse_proxy /*js https://caddyserver.com`? I don't think we can get content-type from request.

How do I write for html only, excluding js,css, and all any other files?

**Comment by mholt** [comment]
> I don't think we can get content-type from request,

Depends on your application; if it's for a .js file, then it will be JavaScript; if for .css, then style sheet, if for .html, then an HTML file; etc.

> So basically handle_response is not for handling response, but to replace with new one instead?

Currently yes, but if we can find a good implementation for reusing the existing body then I think we will do that. Do you have any suggestions?

**Comment by dausruddin** [comment]
> Do you have any suggestions?

I would prefer having the existing body returned automatically by default. User can send different response if they want to.  
But, this is a biased answer. 

Probably having both option would be logical too? Let the default as it is except give it a much proper name, and then add another directive that will return the body by default.
