### ISSUE TITLE
How append prefix /aaa  on all url?

### ISSUE THREAD

**Issue by PHCSJC** [caddyserver/replace-response#18]
I want to append prefix /aaa  on all url of respond, how write? thanks!

**Comment by francislavoie** [comment]
That's non-trivial. There's no bullet-proof regular expression that could accurately replace all URLs. It entirely depends on the context of the strings (the text surrounding the URLs).

You should configure or change your upstream app to add the prefix.

**Comment by mholt** [comment]
If we make some assumptions, for example, static HTML documents:

```
replace stream {
	` src="/` ` src="/aaa/`
	` href="/` ` href="/aaa/`
}
```
