### ISSUE TITLE
is there a way to specify replace only when its 200 ok response code

### ISSUE THREAD

**Issue by anantshri** [caddyserver/replace-response#23]
I would like to replace text but only when its 200 ok and if there is any other code i would much rather not do replacement.

**Comment by mholt** [comment]
Not possible at this time, but some refactoring of the handler could make it possible to use a [ResponseMatcher](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/responsematchers.go) before employing the transformers. Want to submit a PR? (Sorry for the late reply. Had a baby.)
