### ISSUE TITLE
Replace with environment variables?

### ISSUE THREAD

**Issue by richarddavenport** [caddyserver/replace-response#24]
I'm trying to do this, but it doesn't seem to use the environment variable.
```json
{
  "handler": "replace_response",
  "replacements": [
    {
      "search_regexp": "PORTAL_ENVIRONMENT_APIS_AUTH",
      "replace": "{env.PORTAL_ENVIRONMENT_APIS_AUTH}"
    }
  ]
},
```

**Comment by francislavoie** [comment]
Yeah, looks like this module isn't using the placeholder replacer, which would be necessary to use `{env.*}` syntax.

https://github.com/caddyserver/replace-response/blob/d7523f42f84a2fa09d64c957f1e6795ece355425/handler.go#L99

Simple fix, just need to wire it up by getting the placeholder replacer like this:

```
placeholderRepl := ctx.Value(caddy.ReplacerCtxKey).(*caddy.Replacer)
```

Then using it later like `replacement := placeholderRepl.ReplaceAll(repl.Replace)`.

PRs welcome :+1:

**Comment by richarddavenport** [comment]
I would love to contribute! I have zero golang experience. Maybe now's the time to learn? 😅

**Comment by mholt** [comment]
Thanks Francis -- I went ahead and took care of it real quick :+1:

**Comment by mholt** [comment]
Oh, sorry @richarddavenport -- your comment didn't show up for me until now.

**Comment by richarddavenport** [comment]
Zero reason to be sorry @mholt! I super appreciate this project and you guys!

**Comment by francislavoie** [comment]
@mholt might be worth mentioning in the README that placeholders can be used, but only global ones (not http context ones).

**Comment by mholt** [comment]
True; done.

**Comment by schindld** [comment]
> but only global ones (not http context ones)

So, I can't use this to replace `"<head>" "<head><base href='{http.request.uri}/subfolder/'>"`?

**Comment by mholt** [comment]
Correct, because replacement transformers are generated at server-provisioning time, not request time. It is inefficient to do it for every request. I would be interested in a proposal/PR that can make it possible to do efficiently though!
