### ISSUE TITLE
Update documentation to reference path matchers

### ISSUE THREAD

**Issue by SuspiciousDuck** [caddyserver/replace-response#29]
In the documentation, it doesn't say that you can use path matchers with `replace`. The README file should show something like `replace [matcher] [stream | [re] <search> <replace>]`, to show that path matcher *can* be used with `replace`. It also doesn't mention path matchers in the caddyserver.com documentation.

**Comment by mholt** [comment]
Good point. It is an HTTP handler, so it accepts a matcher token as the first argument in the Caddyfile. We should update the Readme to show this.
