### ISSUE TITLE
Behaviour of ^ and $ in regular expressions

### ISSUE THREAD

**Issue by weibeld** [caddyserver/replace-response#5]
The caret (`^`) and dollar sign (`$`) in regular expressions seem to match beginning and end of the entire body and not beginning and end of a line, even though the latter might be more intuitive and useful.

It's best seen with an example. Consider this Caddyfile:

```caddy
{
  order replace after encode
}

:8080 {
  respond 200 {
    body `Line 1
Line 2
Line 3
Line 4`
  }
  replace re ^[A-Za-z]+ foo
  replace re [0-9]+$ bar
}
```

This is what most people would probably expect the output of a request to be:

```
foo bar
foo bar
foo bar
foo bar
```

However, this is what the actual output is:

```
foo 1
Line 2
Line 3
Line bar
```

The point is that one often wants to match some pattern relative to the beginning or end of a line, and usually `^` and `$` are used for this. Even if it is justified that `^` and `$` mean the beginning and end of the entire string, the line-based use case is very common, and as far as I know there is no other robust way to match the beginning and end of a line without `^` and `$`.

So, is there any possibility to somehow redefine the behaviour of `^` and `$` accordingly?

**Comment by francislavoie** [comment]
You need to set the `m` flag (multi-line mode) for that. You can set a prefix `(?m)` at the front of your regexp to set that flag.

```
(?m)^[A-Za-z]+
```

See the syntax docs: https://github.com/google/re2/wiki/Syntax

**Comment by weibeld** [comment]
This is exactly what I needed, thanks!
