### ISSUE TITLE
How do I concatenate matched group with string without separating them with a space?

### ISSUE THREAD

**Issue by dausruddin** [caddyserver/replace-response#8]
Hi. In the example, you wrote

`replace re "\s+foo(bar|baz)\s+" " foo $1 "`

How do I write the replacement text to be like `foo$1`, removing the space?

`foo$1` and `foo{$1}` doesn't work.

Thank you!

**Comment by francislavoie** [comment]
The syntax for capture groups in replacements is `$1` or `${1}`. Try the latter.

**Comment by dausruddin** [comment]
Thank you. It is working :)
